// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3vPRDkr-jodhB7TTYQzgUOe3TP-ReDKw',
    appId: '1:846255112844:web:ae312c46209a65a6b7b1a9',
    messagingSenderId: '846255112844',
    projectId: 'safetrace-25de3',
    authDomain: 'safetrace-25de3.firebaseapp.com',
    storageBucket: 'safetrace-25de3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeadLWxiNtTMVy91evqS2GLbS569kd9m8',
    appId: '1:846255112844:android:d50361d6cef20936b7b1a9',
    messagingSenderId: '846255112844',
    projectId: 'safetrace-25de3',
    storageBucket: 'safetrace-25de3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsKDdHgR0tL8dExobQ66jMxISLy0boUeA',
    appId: '1:846255112844:ios:6a8243353c6eb489b7b1a9',
    messagingSenderId: '846255112844',
    projectId: 'safetrace-25de3',
    storageBucket: 'safetrace-25de3.firebasestorage.app',
    iosBundleId: 'com.example.fypSafetrace',
  );
}
